db:
  container_name: mattermost_db
  image: moifort/docker-mattermost-db:3.2.0
  restart: unless-stopped
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
app:
  container_name: mattermost
  image: moifort/docker-mattermost-app:3.2.0
  restart: unless-stopped
  links:
    - db:db
  volumes:
    - ./mattermost/config:/mattermost/config:rw
    - ./mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
    - VIRTUAL_HOST=mattermost.my-domain.com,www.mattermost.my-domain.com
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=mattermost.my-domain.com,www.mattermost.my-domain.com
    - LETSENCRYPT_EMAIL=my@mail.com
