postgresql:
  container_name: gitlab_postgresql
  image: sameersbn/postgresql:9.4-20
  restart: unless-stopped
  mem_limit: 70m
  environment:
    - DB_USER=gitlab
    - DB_PASS=K474n461714b
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - ./postgres:/var/lib/postgresql/

gitlab:
  container_name: gitlab_app
  image: quay.io/sameersbn/gitlab:8.10.0
  restart: unless-stopped
  mem_limit: 2048m
  environment:
   - VIRTUAL_HOST=gitlab.my-domain.com
   - VIRTUAL_PORT=80
   - LETSENCRYPT_HOST=gitlab.my-domain.com
   - LETSENCRYPT_EMAIL=my@mail.com
   - GITLAB_HOST=gitlab.my-domain.com
   - GITLAB_HTTPS=true
   - GITLAB_PORT=443
   - SSL_SELF_SIGNED=true
   - GITLAB_SSH_HOST=gitlab.my-domain.com
   - GITLAB_SSH_PORT=1022
   - SMTP_USER=my@gmail.com
   - SMTP_PASS=myPassword
   - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
   - GITLAB_NOTIFY_PUSHER=false
   - GITLAB_EMAIL=my@gmail.com
   - GITLAB_EMAIL_REPLY_TO=my@gmail.com
   - GITLAB_INCOMING_EMAIL_ADDRESS=my@gmail.com
   - GITLAB_SECRETS_DB_KEY_BASE=HflQgcZVsqgN44v3CRtzSGhZDP2hmnf25lnz8pgJcBdkrHgZfwLMNg9bC2JM59vQ
   - GITLAB_BACKUPS=daily
   - GITLAB_BACKUP_TIME=01:00
  links:
   - redis:redisio
   - postgresql:postgresql
  ports:
   - "1022:22"
  volumes:
    - ./gitlab:/home/git/data

redis:
  container_name: gitlab_redis
  image: sameersbn/redis:latest
  restart: unless-stopped

runner:
  container_name: gitlab_runner
  image: gitlab/gitlab-runner:v1.3.3
  restart: unless-stopped
  volumes:
    - ./runner/config.toml:/etc/gitlab-runner/config.toml
    - /var/run/docker.sock:/var/run/docker.sock
